###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: api-racer-redis

    mysql:
      image: mysql:5.7
      container_name: api-racer-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=api-racer
        - MYSQL_DATABASE=api-racer
        - MYSQL_USER=api-racer
        - MYSQL_PASSWORD=api-racer
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: api-racer-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
        - mysql
      ports:
        - 8000:80
      environment:
        - PMA_ARBITRARY=1

    php-fpm:
      build: phpdocker/php-fpm
      container_name: api-racer-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

